WITH RECURSIVE ECOLI_TREE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT e.ID, e.PARENT_ID, t.GENERATION + 1
    FROM ECOLI_DATA e
    JOIN ECOLI_TREE t
      ON e.PARENT_ID = t.ID
)
SELECT ID
FROM ECOLI_TREE
WHERE GENERATION = 3
ORDER BY ID;